[package]
name = "modu"
version = { workspace = true }
authors = { workspace = true }
categories = { workspace = true }
edition = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
description = "A modular game engine"

[features]
gpu = ["dep:modu_gpu", "modu_window?/modu_gpu"]
math = ["dep:modu_math"]
window = ["dep:modu_window"]

[dependencies]
modu_gpu = { workspace = true, optional = true }
modu_math = { workspace = true, optional = true }
modu_window = { workspace = true, optional = true }

[workspace]
members = [
    ".",
    "crates/modu_gpu",
    "crates/modu_math",
    "crates/modu_window",
    "sandbox",
]

[workspace.package]
version = "0.1.0"
authors = ["Noam Stein <noamsteindev@proton.me>"]
categories = ["game-engines"]
edition = "2024"
keywords = ["gamedev", "game-engine"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
modu = { path = "." }
modu_gpu = { path = "crates/modu_gpu" }
modu_math = { path = "crates/modu_math" }
modu_window = { path = "crates/modu_window" }

ggmath = "0.16.6"
pollster = "0.4.0"
wgpu = "29.0.1"
winit = "0.30.13"
