[package]
name = "modu"
description = "A modular game engine written in Rust"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
ecs = ["dep:modu_ecs"]
math = ["dep:modu_math"]

[dependencies]
modu_ecs = { workspace = true, optional = true }
modu_math = { workspace = true, optional = true }

[workspace]
members = [".", "modules/modu_math", "examples/sandbox"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/noam2stein/modu"

[workspace.dependencies]
modu_ecs = { path = "modules/modu_ecs" }
modu_math = { path = "modules/modu_math" }
