[package]
name = "modu_ecs_proc_macros"
description = "Contains proc macros used by modu_ecs"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
venial = { workspace = true }
