[package]
name = "modu_window"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
modu_gpu = ["dep:modu_gpu", "dep:pollster"]

[dependencies]
modu_gpu = { workspace = true, optional = true }

pollster = { workspace = true, optional = true }
winit = { workspace = true }
